# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: webapps
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: vault-auth
#   namespace: webapps
---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mysql-pv
# spec:
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: standard
#   hostPath:
#     path: /tmp/mysql-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: webapps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: webapps
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-MYSQL_ROOT_PASSWORD: "secret/data/mysql"
        vault.hashicorp.com/agent-inject-template-MYSQL_ROOT_PASSWORD: |
          {{- with secret "secret/data/mysql" -}}
          export MYSQL_ROOT_PASSWORD="{{ .Data.data.MYSQL_ROOT_PASSWORD }}"
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-MYSQL_DATABASE: "secret/data/mysql"
        vault.hashicorp.com/agent-inject-template-MYSQL_DATABASE: |
          {{- with secret "secret/data/mysql" -}}
          export MYSQL_DATABASE="{{ .Data.data.MYSQL_DATABASE }}"
          {{- end }}
        vault.hashicorp.com/role: "vault-role"
    spec:
      serviceAccountName: vault-auth
      containers:
      - name: mysql
        image: mysql:8
        command: ["/bin/sh", "-c"]
        args:
          - "while [ ! -s /vault/secrets/mysql_root_password ]; do echo 'Waiting for Vault secrets...'; sleep 2; done; \
             source /vault/secrets/mysql_root_password; \
             source /vault/secrets/mysql_database; \
             exec docker-entrypoint.sh mysqld"
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: webapps
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vault-role"
        vault.hashicorp.com/agent-inject-secret-config.txt: "secret/data/bankapp/config"
        vault.hashicorp.com/agent-inject-template-config.txt: |
          {{- with secret "secret/data/bankapp/config" -}}
          MYSQL_USERNAME={{ .Data.data.username }}
          MYSQL_PASSWORD={{ .Data.data.password }}
          MYSQL_DATABASE={{ .Data.data.database }}
          MYSQL_HOST=mysql-service
          MYSQL_PORT=3306
          {{- end }}
    spec:
      serviceAccountName: vault-auth
      automountServiceAccountToken: true
      containers:
        - name: bankapp
          image: neet95402927/bankapp1:v161
          command: ["/bin/sh", "-c"]
          args:
            - |
              while [ ! -s /vault/secrets/config.txt ]; do
                echo 'Waiting for Vault secrets...'
                sleep 2
              done
              . /vault/secrets/config.txt
              exec java -jar /app/bankapp.jar
          ports:
            - containerPort: 8080
          # DO NOT define 'vault-secrets' in volumeMounts — Vault injector handles it

---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
  namespace: webapps
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: bankapp
