---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: webapps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: webapps
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vault-role"

        # Inject MySQL root password
        vault.hashicorp.com/agent-inject-secret-mysql_root_password: "secret/mysql"
        vault.hashicorp.com/agent-inject-template-mysql_root_password: |
          {{- with secret "secret/mysql" -}}
          export MYSQL_ROOT_PASSWORD="{{ .Data.data.MYSQL_ROOT_PASSWORD }}"
          {{- end }}

        # Inject MySQL database name
        vault.hashicorp.com/agent-inject-secret-mysql_database: "secret/mysql"
        vault.hashicorp.com/agent-inject-template-mysql_database: |
          {{- with secret "secret/mysql" -}}
          export MYSQL_DATABASE="{{ .Data.data.MYSQL_DATABASE }}"
          {{- end }}
    spec:
      serviceAccountName: vault-auth
      containers:
      - name: mysql
        image: mysql:8
        command: ["/bin/sh", "-c"]
        args:
          - |
            while [ ! -s /vault/secrets/mysql_root_password ]; do
              echo 'Waiting for Vault secrets...';
              sleep 2;
            done
            while [ ! -s /vault/secrets/mysql_database ]; do
              echo 'Waiting for Vault secrets...';
              sleep 2;
            done

            source /vault/secrets/mysql_root_password
            source /vault/secrets/mysql_database

            exec docker-entrypoint.sh mysqld
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: webapps
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vault-role"

        # Inject bankapp config
        vault.hashicorp.com/agent-inject-secret-config.txt: "secret/bankapp/config"
        vault.hashicorp.com/agent-inject-template-config.txt: |
          {{- with secret "secret/bankapp/config" -}}
          MYSQL_USERNAME={{ .Data.data.username }}
          MYSQL_PASSWORD={{ .Data.data.password }}
          MYSQL_DATABASE={{ .Data.data.database }}
          MYSQL_HOST=mysql-service
          MYSQL_PORT=3306
          {{- end }}
    spec:
      serviceAccountName: vault-auth
      automountServiceAccountToken: true
      containers:
        - name: bankapp
          image: neet95402927/bankapp1:v161
          command: ["/bin/sh", "-c"]
          args: |
            while [ ! -s /vault/secrets/config.txt ]; do
              echo 'Waiting for Vault secrets...';
              sleep 2;
            done

            . /vault/secrets/config.txt

            exec java -jar /app/bankapp.jar
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
  namespace: webapps
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: bankapp
