apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-tokenreview-clusterrole
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts", "serviceaccounts/token", "pods", "secrets"]
    verbs: ["get", "list"]
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-tokenreview-clusterrole
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: vault
